apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svc_name }}
  labels:
    app: {{ .Values.svc_labels}}
spec:
  type: NodePort
  selector:
    app: {{ .Values.labels_app }}
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30002
