#name: Publish Docker image
#
#on:
#  push:
#    branches: ['master']

#jobs:
#  push_to_registry:
#    name: Push Docker image to Docker Hub
#    runs-on: ubuntu-latest
#    steps:
#      - name: Check out the repo
#        uses: actions/checkout@v2
#      
#      - name: Login to Docker Hub
#        id: login
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#      
#      - name: Build Docker image
#        run: docker build -t image:latest .
#      
#      - name: Push Docker image to Docker Hub
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          push: true
#          tags: |
#            peto2505/website:latest









name: Publish Docker image and Deploy to GKE

on:
  push:
    branches: ['master']

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        id: login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker image
        run: docker build -t peto2505/website:latest .
      
      - name: Push Docker image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            peto2505/website:latest

  deploy_to_gke:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    needs: push_to_registry
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.5.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker to use gcloud
        run: |
          gcloud auth configure-docker

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/peto2505/website:${{ github.sha }} .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/peto2505/website:${{ github.sha }}

      - name: Set Kubernetes credentials
        uses: google-github-actions/setup-gke@v0.4.0
        with:
          cluster_name: cluster-1
          location: europe-central2-a
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to GKE
        run: |
          kubectl set image deployment/front-deployment front=gcr.io/${{ secrets.GCP_PROJECT_ID }}/peto2505/website:${{ github.sha }}

