name: Build and Deploy to GKE

on:
  push:
    branches: [ "master" ]

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Build Docker image
      run: |
        gcloud auth configure-docker
        gcloud auth list
        docker build -t gcr.io/kinetic-object-413113/my-img:red .
        docker images
        docker push gcr.io/kinetic-object-413113/my-img:red

    - name: Deploy to GKE
      run: |
        sudo apt-get update && sudo apt-get install -y google-cloud-sdk
        gcloud container clusters get-credentials cluster-1 --zone europe-central2-a --project kinetic-object-413113
        kubectl set image deployment/front-deployment front=gcr.io/kinetic-object-413113/my-img:red --record

    - name: Wait for rollout to complete
      run: |
        kubectl rollout status deployment/front-deployment
        

