name: GCP Authentication Example

on:
  push:
    branches:
      - master

jobs:
  authenticate:
    name: Authenticate with GCP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_file: kinetic-object-413113-3739451ce669.json

      - name: List GCP Projects
        run: |
          gcloud projects list || echo "Failed to list GCP projects"
