name: Publish Docker image to GCP Container Registry

on:
  push:
    branches: ['master']

jobs:
  push_to_gcr:
    name: Push Docker image to GCP Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Configure Docker CLI
        uses: google-github-actions/auth@v0
        with:
          service-account-key: ${{ secrets.GCP_SA_KEY }}
      
      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/website:latest .
          docker images # Optionally, you can list Docker images to verify the build

      - name: Push Docker image to GCP Container Registry
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/website:latest








