name: Build and Deploy to GKE

on:
  push:
    branches: [ "master" ]

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Build Docker image
      run: |
         docker images 
         gcloud auth configure-docker eu-central2-a.pkg.dev
         docker build -t eu-central2-a.pkg.dev/kinetic-object-413113/my-img:why .
         docker push eu-central2-a.pkg.dev/kinetic-object-413113/gcr.io/my-img:why
