name: Build and Deploy to GKE

on:
  push:
    branches: [ "master" ]

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Authenticate to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        docker build -t ${DOCKER_USERNAME}/my-img:${GITHUB_WORKFLOW_SHA} .
        docker images
        docker push ${DOCKER_USERNAME}/my-img:${GITHUB_WORKFLOW_SHA}

