name: Build and Deploy to GKE

on:
  push:
    branches: [ "master" ]

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Build Docker image
      run: |
        gcloud auth configure-docker
        docker build -t gcr.io/kinetic-object-413113/my-img:red .
        docker images
        docker push gcr.io/kinetic-object-413113/my-img:red


    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        project_id: kinetic-object-413113

    - uses: simenandre/setup-gke-gcloud-auth-plugin@v1
    - uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: my-cluster
        location: us-central1-a
    - run: |
        kubectl set image deployment/front-deployment front=gcr.io/kinetic-object-413113/my-img:row 
        kubectl get pods

#    - name: Wait for rollout to complete
#      run: |
#       kubectl rollout status deployment/front-deployment
        

